import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import fs from 'fs';
import path from 'path';

const apiTarget = process.env.API_PROXY_TARGET || 'https://localhost:3443';

// Serve the dev server over HTTPS so that Secure cookies work correctly.
// Certs are generated by scripts/generate-certs.sh into backend/certs/.
// In Docker the same files are mounted at /app/certs/ via docker-compose.
const certPath = process.env.TLS_CERT_PATH || path.resolve(__dirname, '../backend/certs/server.crt');
const keyPath = process.env.TLS_KEY_PATH || path.resolve(__dirname, '../backend/certs/server.key');
const httpsConfig = fs.existsSync(certPath) && fs.existsSync(keyPath)
  ? { cert: fs.readFileSync(certPath), key: fs.readFileSync(keyPath) }
  : undefined;

export default defineConfig({
  plugins: [vue()],
  server: {
    host: '0.0.0.0',
    port: 8443,
    https: httpsConfig,
    proxy: {
      '/api': {
        target: apiTarget,
        changeOrigin: true,
        secure: false
      }
    }
  }
});
